"use client";

import { useRef, useState } from "react";
import * as tus from "tus-js-client";
import { createClient, SupabaseNotConfiguredError } from "@/lib/supabase/client";
import { recordMediaUpload } from "@/app/(app)/actions";

type UploadItem = { id:string; name:string; status:"uploading"|"done"|"error"; progress:number; message?:string };
const MAX_FILE_SIZE=500*1024*1024;const THUMB_MAX=1600;const THUMB_QUALITY=.78;const TUS_CHUNK_SIZE=6*1024*1024;
function mediaTypeFor(mime:string):"image"|"video"|"raw"{if(mime.startsWith("image/"))return"image";if(mime.startsWith("video/"))return"video";return"raw"}
function validateFile(file:File):string|null{if(file.size<=0)return"This file is empty.";if(file.size>MAX_FILE_SIZE)return"File is larger than the 500 MB limit.";if(!file.type.startsWith("image/")&&!file.type.startsWith("video/"))return"Only photo and video files are supported.";return null}
async function makeThumbnail(file:File):Promise<Blob|null>{if(!file.type.startsWith("image/")||file.type==="image/gif")return null;try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,THUMB_MAX/Math.max(bitmap.width,bitmap.height));const width=Math.max(1,Math.round(bitmap.width*scale));const height=Math.max(1,Math.round(bitmap.height*scale));const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d",{alpha:false});if(!ctx){bitmap.close();return null}ctx.drawImage(bitmap,0,0,width,height);bitmap.close();return await new Promise(resolve=>canvas.toBlob(resolve,"image/webp",THUMB_QUALITY))}catch{return null}}
function directStorageEndpoint(supabaseUrl:string){const url=new URL(supabaseUrl);const projectId=url.hostname.split(".")[0];if(!projectId)throw new Error("Invalid Supabase URL.");return `https://${projectId}.storage.supabase.co/storage/v1/upload/resumable`}
async function resumableUpload(file:File,path:string,supabase:ReturnType<typeof createClient>,onProgress:(progress:number)=>void){const{data:{session},error:sessionError}=await supabase.auth.getSession();if(sessionError||!session?.access_token)throw new Error("Your session expired. Please sign in again.");const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL;if(!supabaseUrl)throw new Error("Supabase URL is not configured.");return new Promise<void>((resolve,reject)=>{const upload=new tus.Upload(file,{endpoint:directStorageEndpoint(supabaseUrl),retryDelays:[0,3000,5000,10000,20000],headers:{authorization:`Bearer ${session.access_token}`},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,chunkSize:TUS_CHUNK_SIZE,metadata:{bucketName:"media",objectName:path,contentType:file.type||"application/octet-stream",cacheControl:"3600"},onError:error=>reject(error),onProgress:(uploaded,total)=>onProgress(total?Math.round(uploaded/total*100):0),onSuccess:()=>resolve()});upload.findPreviousUploads().then(previous=>{const previousUpload=previous[0];if(previousUpload)upload.resumeFromPreviousUpload(previousUpload);upload.start()}).catch(reject)})}
export function MediaUploader({workspaceId,projectId}:{workspaceId:string;projectId:string}){const[items,setItems]=useState<UploadItem[]>([]);const[notConfigured,setNotConfigured]=useState(false);const inputRef=useRef<HTMLInputElement>(null);async function uploadFiles(files:FileList|null){if(!files||files.length===0)return;let supabase;try{supabase=createClient()}catch(err){if(err instanceof SupabaseNotConfiguredError)setNotConfigured(true);return}for(const file of Array.from(files)){const id=crypto.randomUUID();const validationError=validateFile(file);if(validationError){setItems(prev=>[...prev,{id,name:file.name,status:"error",progress:0,message:validationError}]);continue}setItems(prev=>[...prev,{id,name:file.name,status:"uploading",progress:0}]);const safeName=file.name.replace(/[^a-zA-Z0-9.\-_]/g,"_");const token=`${Date.now()}-${crypto.randomUUID()}`;const path=`${workspaceId}/${projectId}/${token}-${safeName}`;try{await resumableUpload(file,path,supabase,progress=>setItems(prev=>prev.map(i=>i.id===id?{...i,progress}:i)))}catch(error){const message=error instanceof Error?error.message:"Upload failed.";setItems(prev=>prev.map(i=>i.id===id?{...i,status:"error",message}:i));continue}let thumbnailPath:string|null=null;if(file.type.startsWith("image/")){const thumb=await makeThumbnail(file);if(thumb){thumbnailPath=`${workspaceId}/${projectId}/thumbs/${token}.webp`;const{error:thumbError}=await supabase.storage.from("media").upload(thumbnailPath,thumb,{contentType:"image/webp",cacheControl:"31536000",upsert:false});if(thumbError)thumbnailPath=null}}
const result=await recordMediaUpload({projectId,fileName:safeName,originalName:file.name,mimeType:file.type||"application/octet-stream",fileSize:file.size,storagePath:path,thumbnailPath,mediaType:mediaTypeFor(file.type||"")});if("error"in result){const cleanup=[path,...(thumbnailPath?[thumbnailPath]:[])];const{error:cleanupError}=await supabase.storage.from("media").remove(cleanup);const message=cleanupError?`${result.error} Upload cleanup also failed; please retry or contact support.`:result.error;setItems(prev=>prev.map(i=>i.id===id?{...i,status:"error",message}:i));continue}setItems(prev=>prev.map(i=>i.id===id?{...i,status:"done",progress:100}:i))}if(inputRef.current)inputRef.current.value=""}if(notConfigured)return <div className="mt-4 border border-dashed border-gray-300 rounded-2xl p-6 text-center text-sm text-gray-500">Storage isn&rsquo;t configured yet. Uploads will work once Supabase credentials are set for this deployment.</div>;return <div className="mt-4"><div className="border border-dashed border-gray-300 rounded-2xl p-6 text-center flex flex-col items-center gap-2" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();uploadFiles(e.dataTransfer.files)}}><strong className="text-sm">Drop files here</strong><span className="text-xs text-gray-400">Photos • Video · resumable uploads · up to 500 MB each</span><button type="button" onClick={()=>inputRef.current?.click()} className="border border-gray-300 rounded-full px-4 py-2 text-sm mt-2">Select files</button><input ref={inputRef} type="file" multiple accept="image/*,video/*" className="hidden" onChange={e=>uploadFiles(e.target.files)}/></div>{items.length>0&&<ul className="mt-3 space-y-1.5">{items.map(item=><li key={item.id} className="text-xs bg-gray-50 rounded-lg px-3 py-2"><div className="flex items-center justify-between gap-3"><span className="truncate">{item.name}</span><span className={`shrink-0 ${item.status==="done"?"text-green-700":item.status==="error"?"text-red-600":"text-gray-500"}`}>{item.status==="uploading"?`${item.progress}%`:item.status==="done"?"Uploaded":item.message||"Failed"}</span></div>{item.status==="uploading"&&<div className="mt-2 h-1.5 overflow-hidden rounded-full bg-gray-200"><div className="h-full bg-black transition-[width] duration-200" style={{width:`${item.progress}%`}}/></div>}</li>)}</ul>}</div>}
