import type { Metadata } from "next";
import { LegalShell } from "@/components/legal/LegalShell";

export const metadata: Metadata = { title: "Privacy Policy — RAWI", description: "How RAWI collects, uses and protects personal data." };

export default function PrivacyPage() {
  return (
    <LegalShell eyebrow="PRIVACY AT RAWI" title="Privacy Policy" updated="28 August 2026">
      <section><p>This Privacy Policy explains how RAWI (&ldquo;RAWI&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) handles personal data when creators, their team members and gallery visitors use the RAWI website, applications and client galleries (the &ldquo;Service&rdquo;). RAWI currently operates from the United Arab Emirates. Privacy requests may be sent to <a href="mailto:ali.acc2012@gmail.com">ali.acc2012@gmail.com</a>.</p></section>
      <section><h2>1. Who controls the data</h2><p>RAWI controls account, billing, support and Service-usage data. A creator who uploads media or collects information from a client through a gallery generally controls that client data; RAWI processes it to provide the Service on the creator&apos;s instructions. Creators are responsible for having the permissions and notices required to upload and share their clients&apos; content.</p></section>
      <section><h2>2. Data we collect</h2><ul><li>Account and workspace information, such as name, email address, authentication records, studio name, logo and preferences.</li><li>Creator content, including uploaded photos, videos, thumbnails, gallery titles, project details and branding.</li><li>Gallery interaction data, such as access events, downloads, favorites, approvals, comments and client-provided names where enabled.</li><li>Plan and transaction information, including the selected plan, payment status and payment-provider reference. RAWI does not intentionally store complete payment-card details.</li><li>Technical and security data, such as device/browser information, IP-derived information, logs, error reports and records needed to protect accounts and operate the Service.</li><li>Communications sent to RAWI for support, privacy or business enquiries.</li></ul></section>
      <section><h2>3. How we use data</h2><ul><li>Provide accounts, uploads, galleries, sharing, downloads, feedback, analytics and billing.</li><li>Authenticate users, prevent abuse, investigate errors and secure the Service.</li><li>Communicate about verification, password resets, transactions, support and material Service changes.</li><li>Improve performance and understand how features are used.</li><li>Meet legal, regulatory, accounting and dispute-resolution obligations.</li></ul><p>We process data where necessary to provide the Service, comply with law, pursue legitimate operational and security interests, or where valid consent has been provided.</p></section>
      <section><h2>4. Service providers and international processing</h2><p>RAWI uses specialist providers for hosting, database, authentication, storage, deployment and payments, including Supabase, Vercel and Ziina. These providers process data only to perform services for RAWI under their own contractual and security obligations. Data may be processed outside the UAE. Where required, RAWI uses appropriate safeguards for international transfers.</p></section>
      <section><h2>5. Sharing and disclosure</h2><p>We do not sell personal data. We may disclose it to the creator who controls a gallery, authorised workspace members, contracted service providers, professional advisers, or authorities where required by law. Gallery content is disclosed to people who receive or access its link, subject to any password and expiry settings chosen by the creator.</p></section>
      <section><h2>6. Retention and deletion</h2><p>We retain data for as long as needed to provide the Service, maintain security, resolve disputes and meet legal obligations. Gallery availability may also depend on the creator&apos;s plan and settings. Account holders may request account or personal-data deletion by emailing us. Some information may remain for a limited period in secure backups or where retention is legally required.</p></section>
      <section><h2>7. Your choices and rights</h2><p>Subject to applicable UAE law, you may request access, correction, deletion, restriction or transfer of your personal data, object to certain processing, or withdraw consent where processing relies on consent. You may also raise a concern with the competent UAE data-protection authority. We may need to verify your identity before completing a request.</p></section>
      <section><h2>8. Security</h2><p>RAWI uses access controls, private storage, encrypted connections, scoped permissions and other reasonable technical and organisational safeguards. No online service can guarantee absolute security. Users must protect their credentials and promptly report suspected unauthorised access.</p></section>
      <section><h2>9. Children</h2><p>The Service is intended for professional creators and users aged 18 or over. Creators must not knowingly use RAWI to collect personal data from children without the authority, consent and protections required by applicable law.</p></section>
      <section><h2>10. Changes and contact</h2><p>We may update this Policy when the Service or legal requirements change. Material changes will be communicated through the Service or other appropriate means. Questions and requests may be sent to <a href="mailto:ali.acc2012@gmail.com">ali.acc2012@gmail.com</a>.</p></section>
    </LegalShell>
  );
}
