import type { Metadata } from "next";
import { LegalShell } from "@/components/legal/LegalShell";

export const metadata: Metadata = { title: "Terms of Service — RAWI", description: "Terms governing use of the RAWI creator delivery platform." };

export default function TermsPage() {
  return (
    <LegalShell eyebrow="THE RULES OF THE SERVICE" title="Terms of Service" updated="28 August 2026">
      <section><p>These Terms govern access to and use of RAWI&apos;s website, creator workspace and client galleries (the &ldquo;Service&rdquo;). By creating an account or using the Service, you agree to these Terms. RAWI currently operates from the United Arab Emirates and may be contacted at <a href="mailto:ali.acc2012@gmail.com">ali.acc2012@gmail.com</a>.</p></section>
      <section><h2>1. Eligibility and accounts</h2><p>You must be at least 18 years old and legally able to enter a contract. You must provide accurate account information, protect your credentials and accept responsibility for activity under your account. Tell us promptly if you believe an account has been compromised.</p></section>
      <section><h2>2. The RAWI Service</h2><p>RAWI helps creators upload, organise, present and deliver media through client galleries. Features, storage, active-gallery limits and gallery availability depend on the selected plan. We may improve or modify features while preserving the essential value of an active paid plan.</p></section>
      <section><h2>3. Your content and permissions</h2><p>You retain ownership of content you upload. You grant RAWI a limited, non-exclusive licence to host, copy, process, create technical previews of, transmit and display that content only as needed to operate and improve the Service. This licence ends when the content is deleted, subject to reasonable backup and legal-retention periods.</p><p>You confirm that you have all rights, releases and permissions needed to upload, process and share the content, including permissions relating to clients, identifiable people, music, brands and locations. You control who receives gallery links and are responsible for using available password and expiry controls appropriately.</p></section>
      <section><h2>4. Acceptable use</h2><p>You must not use RAWI to upload or distribute unlawful, infringing, deceptive, abusive, exploitative or malicious content; violate privacy or intellectual-property rights; interfere with security; probe or overload the Service; distribute malware; impersonate others; or resell access without permission. We may restrict or remove content reasonably believed to breach these Terms or law.</p></section>
      <section><h2>5. Client galleries</h2><p>Gallery links may allow invited visitors to preview, download, favorite, approve or comment on content. Creators are responsible for gallery settings, recipients and client communications. Anyone receiving a link must use the gallery only for its intended purpose and must not bypass access controls.</p></section>
      <section><h2>6. Plans, payment and renewal</h2><p>Prices, storage and plan features are shown at checkout or on the pricing page. Paid access is processed by an external payment provider. Taxes may apply. Unless checkout expressly states that automatic renewal is enabled, payment purchases access for the stated billing period and requires a new payment to continue after expiry. Failed, reversed or expired payments may result in downgrade or restricted access.</p><p>Except where applicable law requires otherwise, fees already charged are not refundable after paid storage or plan benefits have been used. If the Service fails materially or a charge is incorrect, contact us promptly so we can investigate. Nothing in these Terms limits mandatory UAE consumer rights.</p></section>
      <section><h2>7. Free plan and storage</h2><p>The Free plan may limit storage, active galleries and availability duration. Content or galleries may become unavailable after the stated period or when limits are exceeded. You are responsible for maintaining your own original files and backups; RAWI is a delivery platform and must not be your only archive.</p></section>
      <section><h2>8. Availability and third-party services</h2><p>We aim to provide a reliable Service but cannot promise uninterrupted availability. Hosting, storage, authentication and payment functions depend partly on third-party providers. Maintenance, security events, internet conditions and provider outages may temporarily affect access.</p></section>
      <section><h2>9. Suspension and termination</h2><p>You may stop using RAWI at any time and may request account deletion. We may suspend or terminate access for non-payment, serious or repeated breaches, security risk, unlawful activity or where required by law. Where reasonably possible, we will provide notice and an opportunity to export content before permanent closure, unless doing so would create legal or security risk.</p></section>
      <section><h2>10. Disclaimers and liability</h2><p>The Service is provided with reasonable care and skill, but results also depend on user devices, internet connections, uploaded files and third-party services. To the maximum extent permitted by law, RAWI is not responsible for indirect or consequential loss, lost profits, lost opportunities or loss caused by a user&apos;s failure to maintain original backups. Nothing excludes liability that cannot legally be excluded.</p></section>
      <section><h2>11. Governing law and changes</h2><p>These Terms are governed by the laws of the United Arab Emirates. Disputes are subject to the competent courts of the UAE unless mandatory consumer law requires otherwise. We may update these Terms to reflect Service or legal changes; material changes will be communicated appropriately and will apply prospectively.</p></section>
      <section><h2>12. Contact</h2><p>Questions, legal notices and support enquiries may be sent to <a href="mailto:ali.acc2012@gmail.com">ali.acc2012@gmail.com</a>.</p></section>
    </LegalShell>
  );
}
